{"timestamp": "2017-09-12T08:46:37.044846Z", "level": "CRITICAL", "message": "Unhandled exception: %s", "system": "Windows 8.1", "gh_handle": "faklijta", "command": "C:\\Users\\Attila\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\gf config https://github.com/greenfox-academy/teaching-materials/blob/master/workshop/functions-and-arrays/python.md", "feature": "CONFIG", "type": "<class 'http.client.RemoteDisconnected'>", "value": "Exception: Remote end closed connection without response", "traceback": "File \"c:\\users\\attila\\appdata\\local\\programs\\python\\python36-32\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"c:\\users\\attila\\appdata\\local\\programs\\python\\python36-32\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"C:\\Users\\Attila\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\gf.exe\\__main__.py\", line 9, in <module>\n    sys.exit(main())\n  File \"c:\\users\\attila\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\gf\\app_starter.py\", line 15, in main\n    app_controller.run()\n  File \"c:\\users\\attila\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\gf\\app_controller.py\", line 11, in run\n    task_check(get_command_argument())()\n  File \"c:\\users\\attila\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\gf\\app_controller.py\", line 35, in config_start\n    config_service.start()\n  File \"c:\\users\\attila\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\gf\\config\\config_service.py\", line 12, in start\n    github.get_token(credential)\n  File \"c:\\users\\attila\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\external\\web\\github.py\", line 14, in get_token\n    payload, \"\"))\n  File \"c:\\users\\attila\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\external\\web\\http_request_handler.py\", line 16, in http_request_handling\n    response = http_connection.getresponse().read().decode('utf-8')\n  File \"c:\\users\\attila\\appdata\\local\\programs\\python\\python36-32\\lib\\http\\client.py\", line 1331, in getresponse\n    response.begin()\n  File \"c:\\users\\attila\\appdata\\local\\programs\\python\\python36-32\\lib\\http\\client.py\", line 297, in begin\n    version, status, reason = self._read_status()\n  File \"c:\\users\\attila\\appdata\\local\\programs\\python\\python36-32\\lib\\http\\client.py\", line 266, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\""}
